services:
  frontend:
    container_name: frontend
    stop_grace_period: 1s
    ports:
      - 3000:3000
    volumes:
      - .:/app
    build:
      context: .
    networks:
      - sportportal_default

networks:
  sportportal_default:
    driver: bridge
    external: true
