services:
  application_db:
    image: postgres:latest
    container_name: application_db
    environment:
      PGPORT: 5433
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: application_db
    ports:
      - "5433:5433"
    volumes:
      - application_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "application_db", "-h", "localhost", "-p", "5433"]
      interval: 5s
      timeout: 50s
    networks:
        - sportportal_default

  application_handling:
    container_name: application_handling
    volumes:
      - .:/app
    build:
      context: .
    networks:
      - sportportal_default
    depends_on:
      application_db:
        condition: service_healthy
    ports:
      - "8002:8002"

volumes:
  application_pgdata:

networks:
  sportportal_default:
    driver: bridge
    external: true
